### ISSUE TITLE
Habit 조회 API

### ISSUE THREAD

**Issue by worjs** [kugods-HabitTama/dahae-server#16]
기획상 Habit 조회 API는 두가지 버전이 있을 것 같은데요,
1. 전체 Habit을 조회하는 API입니다. 단순히 Habit List를 확인할 때 쓰일 것으로 보입니다.
2. 입력으로 특정 날짜를 받으면, 해당 일의 Habit들의 정보를 내려주는 API입니다.
   - HabitRecord들을 내려준다고 생각하시면 되겠습니다.
   - 해당 요일에 수행해야하는 Habit들을 리스트업하고, 진행도를 포함해서 내려주시면 되겠습니다. 진행도가 없으면 0으로 내려주면 됩니다.
   - 1번의 Habit에서 사용되는 Dto를 재사용하고, 여기에 진행도만 추가해서 별도의 Dto를 만드는 구조로 작성해주세요.

**Comment by yunz0926** [comment]
스키마 논의한 후 시간이 지나서, Habit Record 관련하여 헷갈리는 부분이 있어 코멘트 남깁니다 ㅠㅠ


**Habit을 토대로 Habit Record가 생성되는 시점이 언제일까요 ?**

특정 날짜를 입력으로 받았을 때 Habit 정보를 내려주는 경우가 두가지로 생각됩니다.
   1) 이미 지난 날짜에 대한 Habit 기록을 조회하는 경우
   2) 아직 지나지않은 날짜에 대한 Habit 투두를 조희하는 경우

2)번의 경우 백에서 Habit(Habit Record X) 리스트만 리턴해주고 요일별로 보여주는 건 프론트쪽에서 처리하는 식으로 얘기했던 것 같은데,
당일 Habit의 경우 진행률, 달성 여부 등이 수정 가능해야하기 때문에 Habit Record 형태로 DB에 저장되어야할 것 같습니다.

저희가 이전에 Habit Record 생성시점에 대해 논의했던 내용 기억나시는 분은 코멘트 남겨주시면 감사하겠습니당
