### ISSUE TITLE
회원가입, 로그인 관련 api 개발

### ISSUE THREAD

**Issue by worjs** [kugods-HabitTama/dahae-server#6]
## Todo
카카오 연동 관련해서 백엔드가 할만한 태스크는 다음과 같습니다.
1. 회원가입
입력으로 카카오 account_id과 name, os정보를 받아서 db에 등록합니다.
2. 로그인
로그인은 아래와 같은 로직으로 진행됩니다.
    1. 입력으로 카카오 access token을 받아서, 카카오 서버에 이 access token에 해당하는 account_id를 가져옵니다.
    2. account_id가 db에 있는지 확인한 후 로그인 판정합니다.
    3. 유저에게 jwt access token을 리턴합니다.
    
   다만, 위 과정에서 카카오 서버에 access token 보내서 account_id를 가져오는 부분은 현재 등록이 안되어 있어서 바로 수행하기 어려우니, 이 부분은 별도의 함수로 분리해서 빼고 개발하시면 되겠습니다. ex) access token을 input으로 주지만 return으로 mock data인 account_id를 리턴.
    
3. 닉네임 중복체크
이건 필수는 아닌데, 만약 클라이언트단에서 실시간으로 특정 닉네임이 중복인지 아닌지 검사를 한다면 필요해지는 api입니다. input으로 name을 받으면, 해당 name이 db에 존재하는지 확인해서 결과를 리턴합니다.

## Additional Context
- 전부 auth라는 모듈을 별도로 생성해서 그쪽에 작성하면 됩니다.
- prisma model이 완성된 상태가 아니여서, repository layer의 prisma 관련 쿼리는 사용할 수 없는데, 임시로 mock data를 사용하거나 편한 방식으로 나머지 부분을 구현하면 되겠습니다!

**Comment by worjs** [comment]
@yunz0926 이거 혹시 작업중이신가요...? 카카오 소셜로그인하면 애플까지 해야하서 그냥 이메일 패스워드 기반으로 가자는 의견이 나와서요ㅠ

**Comment by yunz0926** [comment]
@worjs 다른 얘기가 없어서 작업중이긴했는데, 어제 새벽부터 시작해서 많이 진행하진 못했습니다..! 자체 로그인 구현으로 바뀐건가요 ?

**Comment by worjs** [comment]
@yunz0926 일단 그렇게 갈 것 같아요! 그러면,
1. 회원가입 => email, pw, name, os를 받습니다. pw는 db에 입력하기전에 bcrypt같은 라이브러리 써서 암호화해서 저장합니다.
2. 로그인 => email, pw 받아서 db에서 email로 유저를 조회한 뒤, pw를 복호화해서 비교하고 access token을 생성해서 리턴합니다.

이정도로 변경되겠습니다..!

db도 살짝 변할 것 같은데, 이건 지금 PR올려둘테니 rebase해서 진행하시면 될 것 같아요!
